// Code generated by mockery 2.9.0. DO NOT EDIT.

package querymocks

import (
	context "context"
	query "bunsan-ocr/kit/bus/query"

	mock "github.com/stretchr/testify/mock"
)

// Bus is an autogenerated mock type for the Bus type
type Bus struct {
	mock.Mock
}

// Ask provides a mock function with given fields: _a0, _a1
func (_m *Bus) Ask(_a0 context.Context, _a1 query.Query) (query.Response, error) {
	ret := _m.Called(_a0, _a1)

	var r0 query.Response
	if rf, ok := ret.Get(0).(func(context.Context, query.Query) query.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, query.Query) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *Bus) Register(_a0 query.Type, _a1 query.Handler) {
	_m.Called(_a0, _a1)
}
